seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - page_type: alphabets
    file: ./parsers/alphabets.rb
    disabled: false
  - page_type: categories
    file: ./parsers/categories.rb
    disabled: false